// BLENDIA 豆データベース
// profile: 各軸 1〜5（acidity=酸味, body=コク, sweetness=甘み, bitterness=苦味, aroma=香り, fruity=フルーティさ）
// notes: 固定語彙のフレーバータグ（blend.js の相性表と対応）
// price: 参考価格帯の算出にのみ使用（画面には金額を出さない）

const AXES = [
  { key: "acidity", label: "酸味" },
  { key: "body", label: "コク" },
  { key: "sweetness", label: "甘み" },
  { key: "bitterness", label: "苦味" },
  { key: "aroma", label: "香り" },
  { key: "fruity", label: "フルーティ" },
];

const NOTE_LABELS = {
  citrus: "シトラス",
  floral: "フローラル",
  berry: "ベリー",
  wine: "ワイニー",
  chocolate: "チョコレート",
  nuts: "ナッツ",
  caramel: "キャラメル",
  honey: "はちみつ",
  spice: "スパイス",
  earthy: "アーシー",
  tea: "紅茶",
  tropical: "トロピカル",
};

const ROAST_LABELS = { light: "浅煎り", medium: "中煎り", mediumdark: "中深煎り", dark: "深煎り" };

// 定番レシピ（items: [豆id, 配合比]）
const RECIPES = [
  {
    name: "朝のすっきりブレンド",
    goal: "すっきり・華やか",
    items: [["eth-yirgacheffe", 5], ["tza-kilimanjaro", 5]],
    comment: "浅煎りのエチオピア×タンザニアという定番の組み合わせ。柑橘系の爽やかな酸味と華やかな香りで、目覚めの一杯に。",
  },
  {
    name: "毎日のバランスブレンド",
    goal: "バランス",
    items: [["bra-cerrado", 4], ["col-huila", 3], ["gtm-antigua", 3]],
    comment: "ブラジル・コロンビア・グアテマラを4:3:3で。喫茶店のブレンドの王道構成で、甘み・コク・香ばしさが整った飽きのこない味。",
  },
  {
    name: "夜のどっしりブレンド",
    goal: "どっしり・重厚",
    items: [["idn-mandheling", 5], ["col-huila", 5]],
    comment: "重厚なマンデリンを、甘みのあるコロンビアが受け止める組み合わせ。ミルクにも負けない飲みごたえで、食後や夜のリラックスタイムに。",
  },
  {
    name: "モカ・ジャバ",
    goal: "個性派",
    items: [["idn-mandheling", 6], ["eth-sidamo", 4]],
    comment: "18世紀から続く世界最古のブレンドレシピ。アーシーなマンデリンの土台に、モカのベリー感が跳ねる、対比の妙を楽しむ一杯。",
  },
  {
    name: "華やぎのモーニングブレンド",
    goal: "すっきり・華やか",
    items: [["eth-guji", 5], ["ken-nyeri", 5]],
    comment: "エチオピアの甘い果実味に、ケニアの弾けるような酸味を重ねた、目が覚める華やかさ。休日の朝の一杯に。",
  },
  {
    name: "カフェオレのためのブレンド",
    goal: "どっしり・重厚",
    items: [["idn-mandheling", 6], ["bra-bourbon", 4]],
    comment: "ミルクに負けないマンデリンのコクを、黄ブルボンのはちみつのような甘みが下支え。濃いめに淹れてミルクと1:1で。",
  },
  {
    name: "上品な午後のひととき",
    goal: "バランス",
    items: [["col-emerald", 5], ["gtm-huehue", 5]],
    comment: "エメラルドマウンテンの澄んだ甘みに、ウエウエテナンゴの果実味。雑味なく飲み疲れしない優等生ブレンド。",
  },
  {
    name: "アイス向け深煎りブレンド",
    goal: "どっしり・重厚",
    items: [["idn-mandheling", 5], ["gtm-antigua", 5]],
    comment: "冷やすと苦味が和らぐ深煎り同士。氷で急冷しても骨格が残り、ガムシロなしでもコクのあるアイスに。",
  },
  {
    name: "甘い余韻のスイーツブレンド",
    goal: "バランス",
    items: [["cri-tarrazu", 5], ["bra-bourbon", 5]],
    comment: "ハニープロセスのはちみつ感と黄ブルボンの粘性のある甘さ。デザートに寄り添う、砂糖なしでも甘いカップ。",
  },
  {
    name: "スパイス香る食後の一杯",
    goal: "個性派",
    items: [["ind-ganesha", 6], ["eth-sidamo", 4]],
    comment: "ガネーシャのシナモン香に、モカのベリー感を少量。カレーや食事のあとにすっと寄り添う個性派ブレンド。",
  },
  {
    name: "どっしりネルドリップブレンド",
    goal: "どっしり・重厚",
    items: [["idn-toraja", 5], ["col-huila", 5]],
    comment: "トラジャの土のようなコクを、コロンビアの甘みがまとめる。ネルでゆっくり淹れたい重心の低い一杯。",
  },
  {
    name: "香りを楽しむ贅沢ブレンド",
    goal: "すっきり・華やか",
    items: [["pan-geisha", 2], ["gtm-huehue", 8]],
    comment: "少量のゲイシャがブレンド全体の香りを一段引き上げる。ウエウエテナンゴの安定した甘みが土台。特別な日に。",
  },
  {
    name: "毎朝のマイルドブレンド",
    goal: "バランス",
    items: [["bra-santos", 5], ["col-huila", 5]],
    comment: "サントスの香ばしさとコロンビアの甘み。クセがなく毎日飲んでも飽きない、ブレンドの基本形。",
  },
];

// ブレンドの基礎知識
const GUIDE_TIPS = [
  { title: "ゴールを決めてから組む", body: "「すっきり」「どっしり」など、目指す味を先に決めるのがブレンドの出発点。豆選びはそのあと。" },
  { title: "まずは2種類から", body: "いきなり多くの豆を混ぜると味が濁る原因に。2種類で比率を変えながら試すのが上達の近道。" },
  { title: "多くても4種類まで", body: "豆の種類が増えるほど各豆の個性がぼやける。プロのブレンドも多くは2〜4種で構成されている。" },
  { title: "焙煎度の近い豆を選ぶ", body: "浅煎り×深煎りのように焙煎度が離れすぎると、抽出のバランスが取りにくい。まずは近い焙煎度同士で。" },
  { title: "家庭ではアフターミックス", body: "焙煎後の豆を混ぜる「アフターミックス」なら、雑味が出にくく手軽。生豆から混ぜるプレミックスは焙煎所の技。" },
];

const BEANS = [
  {
    id: "eth-yirgacheffe",
    name: "イルガチェフェ G1 ウォッシュド",
    country: "エチオピア", region: "イルガチェフェ", flag: "🇪🇹",
    process: "ウォッシュド", roast: "light", price: 980,
    variety: "エチオピア在来種", altitude: "1,700〜2,200m", harvest: "10月〜1月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 5, body: 2, sweetness: 4, bitterness: 1, aroma: 5, fruity: 5 },
    notes: ["citrus", "floral", "tea"],
    description: "コーヒーの原産地エチオピアを代表する銘柄。レモンティーのような繊細な口当たりに、ジャスミンを思わせる華やかな香りが立ち上がる。浅煎りシングルの定番でありながら、ブレンドでは少量で全体を明るくする「香りの起爆剤」としても優秀。",
  },
  {
    id: "eth-sidamo",
    name: "シダモ ナチュラル",
    country: "エチオピア", region: "シダモ", flag: "🇪🇹",
    process: "ナチュラル", roast: "light", price: 900,
    variety: "エチオピア在来種", altitude: "1,500〜2,200m", harvest: "10月〜1月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 5 },
    notes: ["berry", "wine", "chocolate"],
    description: "完熟チェリーごと乾燥させるナチュラル精製ならではの、いちごやブルーベリーを思わせる果実感が魅力。ワインのような発酵感のある甘みが余韻に残る。モカフレーバーの原点。",
  },
  {
    id: "eth-guji",
    name: "グジ ナチュラル",
    country: "エチオピア", region: "グジ", flag: "🇪🇹",
    process: "ナチュラル", roast: "light", price: 1050,
    variety: "エチオピア在来種", altitude: "1,800〜2,300m", harvest: "11月〜2月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 5, bitterness: 1, aroma: 5, fruity: 5 },
    notes: ["berry", "floral", "tropical"],
    description: "近年評価が急上昇しているエチオピア南部の産地。いちごジャムのような濃厚な甘さとフローラルな香りが共存し、冷めるほどに果実味が際立つ。",
  },
  {
    id: "eth-kaffa-geisha",
    name: "カッファ ゲイシャ G3",
    country: "エチオピア", region: "カッファ", flag: "🇪🇹",
    process: "ナチュラル", roast: "light", price: 1350,
    variety: "ゲイシャ（エチオピア原種系統）", altitude: "1,800〜2,100m", harvest: "11月〜2月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 2, sweetness: 4, bitterness: 1, aroma: 5, fruity: 5 },
    notes: ["floral", "tropical", "tea"],
    description: "ゲイシャ種の故郷・カッファ地方（ゲシャ村周辺）産。パナマの超高級ゲイシャの原種にあたる系統を、G3グレードなら手の届く価格で楽しめる。華やかな花香とトロピカルな甘さは紛れもなくゲイシャの血筋。",
  },
  {
    id: "ken-nyeri",
    name: "ニエリ AA",
    country: "ケニア", region: "ニエリ", flag: "🇰🇪",
    process: "ウォッシュド", roast: "light", price: 1100,
    variety: "SL28 / SL34", altitude: "1,700〜2,000m", harvest: "10月〜12月（メイン）",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 5, body: 4, sweetness: 4, bitterness: 2, aroma: 4, fruity: 5 },
    notes: ["berry", "citrus", "wine"],
    description: "カシスやグレープフルーツを思わせる鮮烈な酸味と、しっかりしたコクを併せ持つケニアの銘柄。AAは豆の大きさによる等級（品質等級ではない）だが、大粒の豆は良質なロットに多く、酸の質が非常にクリアでジューシーという言葉が最も似合う一杯に仕上がる。",
  },
  {
    id: "tza-kilimanjaro",
    name: "キリマンジャロ AA",
    country: "タンザニア", region: "キリマンジャロ", flag: "🇹🇿",
    process: "ウォッシュド", roast: "medium", price: 780,
    variety: "ブルボン / ケント", altitude: "1,400〜1,800m", harvest: "7月〜12月",
    brew: ["ハンドドリップ", "サイフォン"],
    profile: { acidity: 4, body: 3, sweetness: 3, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["citrus", "nuts"],
    description: "日本でも古くから親しまれる、キリマンジャロ山麓の豆。キリッとした柑橘系の酸味と軽快な飲み口が特徴で、クセがなくブレンドの酸味担当として扱いやすい。",
  },
  {
    id: "rwa-huye",
    name: "フイエ ウォッシュド",
    country: "ルワンダ", region: "フイエ", flag: "🇷🇼",
    process: "ウォッシュド", roast: "light", price: 850,
    variety: "ブルボン", altitude: "1,700〜2,100m", harvest: "3月〜7月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 4 },
    notes: ["citrus", "honey", "floral"],
    description: "「千の丘の国」ルワンダの高地産。オレンジのような明るい酸味とはちみつの甘みがバランスよくまとまり、クリーンで飲み疲れしない。",
  },
  {
    id: "bdi-kayanza",
    name: "カヤンザ ウォッシュド",
    country: "ブルンジ", region: "カヤンザ", flag: "🇧🇮",
    process: "ウォッシュド", roast: "light", price: 880,
    variety: "ブルボン", altitude: "1,700〜2,000m", harvest: "3月〜7月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 4 },
    notes: ["berry", "citrus", "honey"],
    description: "ルワンダの隣国、東アフリカの小国ブルンジの主要産地。赤い果実の甘酸っぱさと紅茶のような繊細さを持ち、スペシャルティ市場で急速に注目を集めている。",
  },
  {
    id: "col-huila",
    name: "ウイラ スプレモ",
    country: "コロンビア", region: "ウイラ", flag: "🇨🇴",
    process: "ウォッシュド", roast: "medium", price: 750,
    variety: "カスティージョ / カトゥーラ", altitude: "1,200〜1,800m", harvest: "年2回（10〜12月 / 4〜6月）",
    brew: ["ハンドドリップ", "フレンチプレス", "エスプレッソ"],
    profile: { acidity: 3, body: 4, sweetness: 4, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["caramel", "berry", "chocolate"],
    description: "コロンビア南部の代表的産地。キャラメルのような甘みと厚みのあるコクがあり、単体でも完成度が高い。どんな豆とも喧嘩しない、ブレンドの土台として万能な一本。",
  },
  {
    id: "col-narino",
    name: "ナリーニョ",
    country: "コロンビア", region: "ナリーニョ", flag: "🇨🇴",
    process: "ウォッシュド", roast: "medium", price: 880,
    variety: "カスティージョ / カトゥーラ", altitude: "1,800〜2,300m", harvest: "3月〜6月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 4 },
    notes: ["citrus", "caramel", "honey"],
    description: "標高2,000mを超える急斜面で育つ高地栽培豆。コロンビアらしい甘さに、高地由来の明るい酸味が加わったエレガントな味わい。",
  },
  {
    id: "col-emerald",
    name: "エメラルドマウンテン",
    country: "コロンビア", region: "アンデス高地（選別ブランド）", flag: "🇨🇴",
    process: "ウォッシュド", roast: "medium", price: 1600,
    variety: "カスティージョ / カトゥーラ", altitude: "1,400〜2,000m", harvest: "年2回（10〜12月 / 4〜6月）",
    brew: ["ハンドドリップ", "サイフォン"],
    profile: { acidity: 3, body: 4, sweetness: 5, bitterness: 2, aroma: 4, fruity: 3 },
    notes: ["caramel", "honey", "chocolate"],
    description: "缶コーヒーの名前として知る人も多いが、本来はコロンビアコーヒー生産者連合会（FNC）が上位数％だけに与える選別ブランド。エメラルドのように磨かれた、豊かな甘みと澄んだコクのバランスは別格。",
  },
  {
    id: "bra-cerrado",
    name: "セラード ナチュラル",
    country: "ブラジル", region: "セラード", flag: "🇧🇷",
    process: "ナチュラル", roast: "medium", price: 680,
    variety: "ムンドノーボ / カトゥアイ", altitude: "900〜1,200m", harvest: "5月〜9月",
    brew: ["ハンドドリップ", "エスプレッソ", "フレンチプレス"],
    profile: { acidity: 2, body: 4, sweetness: 4, bitterness: 3, aroma: 3, fruity: 2 },
    notes: ["nuts", "chocolate", "caramel"],
    description: "世界最大の生産国ブラジルの主力産地。ナッツとチョコレートの香ばしさ、低めの酸味、安定したコク。世界中のブレンドのベースを支える屋台骨的存在。",
  },
  {
    id: "bra-bourbon",
    name: "ブルボン アマレロ",
    country: "ブラジル", region: "スル・デ・ミナス", flag: "🇧🇷",
    process: "パルプドナチュラル", roast: "medium", price: 720,
    variety: "ブルボン アマレロ（黄ブルボン）", altitude: "950〜1,300m", harvest: "5月〜9月",
    brew: ["ハンドドリップ", "エスプレッソ"],
    profile: { acidity: 2, body: 4, sweetness: 5, bitterness: 2, aroma: 3, fruity: 2 },
    notes: ["honey", "nuts", "caramel"],
    description: "黄色く熟す希少品種ブルボン・アマレロ。はちみつのような粘性のある甘さが特徴で、ブレンドに入れると全体の甘みの底上げをしてくれる。",
  },
  {
    id: "bra-santos",
    name: "サントス No.2",
    country: "ブラジル", region: "サンパウロ州ほか（サントス港積み）", flag: "🇧🇷",
    process: "ナチュラル", roast: "medium", price: 680,
    variety: "ブルボン / ムンドノーボ", altitude: "800〜1,100m", harvest: "5月〜9月",
    brew: ["ハンドドリップ", "エスプレッソ", "フレンチプレス"],
    profile: { acidity: 2, body: 3, sweetness: 4, bitterness: 3, aroma: 3, fruity: 2 },
    notes: ["nuts", "chocolate", "caramel"],
    description: "輸出港サントスの名を冠した、日本の喫茶文化を支えてきた最古参ブランド。No.2は事実上の最高等級（欠点ゼロのNo.1は規格上存在しない）。柔らかな苦味と香ばしさで、どんなブレンドにも馴染む懐の深さ。",
  },
  {
    id: "gtm-antigua",
    name: "アンティグア",
    country: "グアテマラ", region: "アンティグア", flag: "🇬🇹",
    process: "ウォッシュド", roast: "mediumdark", price: 820,
    variety: "ブルボン / カトゥーラ", altitude: "1,500〜1,700m", harvest: "1月〜3月",
    brew: ["ハンドドリップ", "エスプレッソ"],
    profile: { acidity: 3, body: 4, sweetness: 4, bitterness: 3, aroma: 4, fruity: 3 },
    notes: ["chocolate", "spice", "caramel"],
    description: "3つの火山に囲まれた盆地で育つ、スモーキーさをまとった豆。ビターチョコとスパイスの風味が深煎りでいっそう映える。重心の低いブレンドを組みたいときの主役。",
  },
  {
    id: "gtm-huehue",
    name: "ウエウエテナンゴ",
    country: "グアテマラ", region: "ウエウエテナンゴ", flag: "🇬🇹",
    process: "ウォッシュド", roast: "medium", price: 890,
    variety: "ブルボン / カトゥーラ", altitude: "1,500〜2,000m", harvest: "1月〜4月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 4, sweetness: 4, bitterness: 2, aroma: 4, fruity: 4 },
    notes: ["berry", "caramel", "citrus"],
    description: "グアテマラ最高地の産地。果実味・甘み・コクの三拍子が揃ったオールラウンダーで、シングルでもブレンドでも破綻しない優等生。",
  },
  {
    id: "cri-tarrazu",
    name: "タラス ハニープロセス",
    country: "コスタリカ", region: "タラス", flag: "🇨🇷",
    process: "ハニー", roast: "light", price: 950,
    variety: "カトゥーラ / カトゥアイ", altitude: "1,200〜1,900m", harvest: "12月〜3月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 5, bitterness: 1, aroma: 4, fruity: 4 },
    notes: ["honey", "citrus", "tropical"],
    description: "ミューシレージ（果肉の粘質）を残して乾燥させるハニープロセスの名手、コスタリカ・タラス地区。名前の通りはちみつのような甘さと、みかんのような優しい酸味。",
  },
  {
    id: "cri-jaguar",
    name: "ジャガーハニー",
    country: "コスタリカ", region: "タラス", flag: "🇨🇷",
    process: "レッドハニー", roast: "medium", price: 950,
    variety: "カトゥーラ / カトゥアイ", altitude: "1,200〜1,600m", harvest: "12月〜3月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 3, body: 3, sweetness: 5, bitterness: 2, aroma: 4, fruity: 4 },
    notes: ["honey", "tropical", "caramel"],
    description: "売上の一部が野生のジャガー保護に充てられるユニークな銘柄。果肉の糖を多めに残すレッドハニー精製で、黒糖のようなコクのある甘さと熟した果実感が両立。ストーリーも味も濃い一杯。",
  },
  {
    id: "pan-geisha",
    name: "ボケテ ゲイシャ",
    country: "パナマ", region: "ボケテ", flag: "🇵🇦",
    process: "ウォッシュド", roast: "light", price: 2400,
    variety: "ゲイシャ", altitude: "1,400〜1,800m", harvest: "1月〜4月",
    brew: ["ハンドドリップ"],
    profile: { acidity: 5, body: 2, sweetness: 4, bitterness: 1, aroma: 5, fruity: 5 },
    notes: ["floral", "citrus", "tropical", "tea"],
    description: "世界のオークション記録を塗り替え続ける伝説の品種。ジャスミンとベルガモットの圧倒的な香りは一度飲むと忘れられない。ブレンドでは1〜2割加えるだけで香りの次元が変わる贅沢なアクセント。",
  },
  {
    id: "hnd-marcala",
    name: "マルカラ",
    country: "ホンジュラス", region: "マルカラ", flag: "🇭🇳",
    process: "ウォッシュド", roast: "medium", price: 700,
    variety: "カトゥーラ / レンピラ", altitude: "1,300〜1,700m", harvest: "12月〜4月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["caramel", "nuts", "honey"],
    description: "中米の隠れた実力派。キャラメルの甘みと穏やかな酸味の素直な味わいで、価格も手頃。デイリーブレンドの増量役として頼れる存在。",
  },
  {
    id: "nic-jinotega",
    name: "ヒノテガ",
    country: "ニカラグア", region: "ヒノテガ", flag: "🇳🇮",
    process: "ウォッシュド", roast: "medium", price: 740,
    variety: "カトゥーラ / ブルボン", altitude: "1,100〜1,500m", harvest: "12月〜3月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 3, body: 4, sweetness: 4, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["caramel", "chocolate", "nuts"],
    description: "ニカラグア最大の産地。ミルクチョコレートのような柔らかな甘みと安定したコクで、中米らしい素直な味の教科書のような豆。",
  },
  {
    id: "mex-altura",
    name: "アルトゥーラ",
    country: "メキシコ", region: "チアパス", flag: "🇲🇽",
    process: "ウォッシュド", roast: "medium", price: 730,
    variety: "ブルボン / ティピカ", altitude: "1,200〜1,700m", harvest: "11月〜3月",
    brew: ["ハンドドリップ", "コールドブリュー"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["nuts", "chocolate", "citrus"],
    description: "「アルトゥーラ」は高地産の意。グアテマラ国境に近いチアパス州の豆は、軽やかな口当たりにナッツの香ばしさとほのかな柑橘感。アイスコーヒーにしても崩れない。",
  },
  {
    id: "per-chanchamayo",
    name: "チャンチャマヨ",
    country: "ペルー", region: "チャンチャマヨ", flag: "🇵🇪",
    process: "ウォッシュド", roast: "medium", price: 720,
    variety: "ティピカ / カトゥーラ", altitude: "1,200〜1,800m", harvest: "4月〜9月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["nuts", "honey", "chocolate"],
    description: "アンデス東麓の渓谷で育つオーガニック栽培が盛んな豆。ナッツの香ばしさと柔らかな甘み。主張は控えめだが、ブレンド全体を丸くまとめる調停役。",
  },
  {
    id: "bol-caranavi",
    name: "カラナビ",
    country: "ボリビア", region: "カラナビ", flag: "🇧🇴",
    process: "ウォッシュド", roast: "light", price: 920,
    variety: "ティピカ / カトゥーラ", altitude: "1,200〜1,700m", harvest: "6月〜10月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 1, aroma: 4, fruity: 4 },
    notes: ["berry", "honey", "floral"],
    description: "アンデスの急峻な谷あいで少量だけ生産される知る人ぞ知る産地。クリーンな甘さと繊細な花香で、「南米のエチオピア」と呼ばれることも。",
  },
  {
    id: "idn-mandheling",
    name: "マンデリン G1",
    country: "インドネシア", region: "スマトラ島 リントン", flag: "🇮🇩",
    process: "スマトラ式", roast: "dark", price: 830,
    variety: "ティピカ系在来種ほか", altitude: "1,100〜1,500m", harvest: "9月〜12月（メイン）",
    brew: ["フレンチプレス", "ネルドリップ", "エスプレッソ"],
    profile: { acidity: 1, body: 5, sweetness: 3, bitterness: 4, aroma: 3, fruity: 1 },
    notes: ["earthy", "spice", "chocolate"],
    description: "スマトラ式という独特の精製が生む、大地を思わせる重厚なコクとハーブ・スパイスの風味。酸味はほぼなく、深煎りの世界の王様。フルーティな豆と合わせる「モカ・ジャバ」型ブレンドは18世紀から続く王道。",
  },
  {
    id: "idn-toraja",
    name: "トラジャ",
    country: "インドネシア", region: "スラウェシ島 タナトラジャ", flag: "🇮🇩",
    process: "スマトラ式", roast: "mediumdark", price: 900,
    variety: "ティピカ系在来種", altitude: "1,300〜1,800m", harvest: "6月〜10月",
    brew: ["ネルドリップ", "フレンチプレス"],
    profile: { acidity: 2, body: 5, sweetness: 4, bitterness: 3, aroma: 3, fruity: 2 },
    notes: ["earthy", "caramel", "spice"],
    description: "「セレベスの名品」と呼ばれる幻の豆。マンデリンの重厚さに上品な甘さを足したような味わいで、どっしり系ブレンドの土台を格上げしてくれる。",
  },
  {
    id: "png-highlands",
    name: "ハイランド AA",
    country: "パプアニューギニア", region: "東ハイランド", flag: "🇵🇬",
    process: "ウォッシュド", roast: "medium", price: 760,
    variety: "ティピカ / ブルボン", altitude: "1,400〜1,900m", harvest: "4月〜9月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 3, body: 4, sweetness: 4, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["tropical", "caramel", "nuts"],
    description: "ジャマイカ・ブルーマウンテンの血統を引く木が高地で育つ。トロピカルフルーツの片鱗を感じる甘みとしっかりしたコク。知名度は低いがコスパは折り紙付き。",
  },
  {
    id: "yem-mattari",
    name: "モカマタリ",
    country: "イエメン", region: "バニーマタル", flag: "🇾🇪",
    process: "ナチュラル", roast: "medium", price: 1300,
    variety: "イエメン在来種", altitude: "1,500〜2,400m", harvest: "10月〜12月",
    brew: ["ハンドドリップ", "サイフォン"],
    profile: { acidity: 4, body: 4, sweetness: 4, bitterness: 2, aroma: 5, fruity: 4 },
    notes: ["wine", "spice", "chocolate", "berry"],
    description: "「コーヒー貴婦人」の異名を持つ、モカ港の名を冠した歴史的銘柄。赤ワインのような芳醇さとスパイシーで複雑な香り。個性が強く、少量でブレンドに気品を与える。",
  },
  {
    id: "ind-malabar",
    name: "モンスーン マラバール",
    country: "インド", region: "マラバール海岸", flag: "🇮🇳",
    process: "モンスーニング", roast: "dark", price: 800,
    variety: "ケント / S795", altitude: "1,000〜1,500m", harvest: "11月〜2月（熟成後出荷）",
    brew: ["エスプレッソ", "ネルドリップ"],
    profile: { acidity: 1, body: 5, sweetness: 3, bitterness: 4, aroma: 3, fruity: 1 },
    notes: ["earthy", "spice", "nuts"],
    description: "季節風に数週間さらして熟成させる特殊製法。酸が抜けて枯れたような独特の深みが生まれる。エスプレッソブレンドのコク出しに使われる通好みの豆。",
  },
  {
    id: "ind-ganesha",
    name: "ガネーシャ",
    country: "インド", region: "カルナタカ州 チクマガルール", flag: "🇮🇳",
    process: "ウォッシュド", roast: "mediumdark", price: 780,
    variety: "S795 / ケント", altitude: "1,000〜1,500m", harvest: "10月〜2月",
    brew: ["ハンドドリップ", "エスプレッソ", "フレンチプレス"],
    profile: { acidity: 2, body: 4, sweetness: 4, bitterness: 3, aroma: 4, fruity: 2 },
    notes: ["spice", "chocolate", "caramel"],
    description: "象の神様の名を冠した、インドコーヒー発祥の地チクマガルール産。シナモンを思わせるスパイス香とビターチョコの甘苦さで、近年日本のロースターの間で人気が急上昇中。カレーのあとの一杯に妙に合う。",
  },
  {
    id: "slv-pacamara",
    name: "パカマラ",
    country: "エルサルバドル", region: "アパネカ", flag: "🇸🇻",
    process: "ウォッシュド", roast: "light", price: 1000,
    variety: "パカマラ", altitude: "1,200〜1,800m", harvest: "12月〜3月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 4 },
    notes: ["tropical", "citrus", "caramel"],
    description: "通常の倍近い大粒の希少品種。トロピカルフルーツの華やかさとまろやかな甘みを併せ持ち、カップ・オブ・エクセレンスの常連。",
  },
  {
    id: "jam-bluemountain",
    name: "ブルーマウンテン No.1",
    country: "ジャマイカ", region: "ブルーマウンテン", flag: "🇯🇲",
    process: "ウォッシュド", roast: "medium", price: 3800,
    variety: "ティピカ", altitude: "900〜1,700m（指定区域）", harvest: "10月〜3月（12〜2月がピーク）",
    brew: ["ハンドドリップ", "サイフォン"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 3 },
    notes: ["nuts", "floral", "honey"],
    description: "「コーヒーの王様」。酸味・甘み・苦味のバランスが黄金比と称される、日本で特に愛されてきた最高級銘柄。突出した個性ではなく、完璧な調和がこの豆の個性。",
  },
  {
    id: "usa-kona",
    name: "コナ エクストラファンシー",
    country: "アメリカ", region: "ハワイ島 コナ", flag: "🇺🇸",
    process: "ウォッシュド", roast: "medium", price: 3200,
    variety: "コナ・ティピカ", altitude: "150〜900m", harvest: "8月〜1月",
    brew: ["ハンドドリップ", "サイフォン"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 3 },
    notes: ["nuts", "citrus", "honey"],
    description: "ハワイ島コナ地区の溶岩土壌で育つ世界三大コーヒーのひとつ。まろやかな甘みとナッツの香ばしさ、かすかな柑橘。ギフトとしても別格の存在感。",
  },
  {
    id: "cub-crystal",
    name: "クリスタルマウンテン",
    country: "キューバ", region: "エスカンブライ山脈", flag: "🇨🇺",
    process: "ウォッシュド", roast: "medium", price: 1900,
    variety: "ティピカ ほか", altitude: "350〜750m", harvest: "9月〜1月",
    brew: ["ハンドドリップ", "サイフォン"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 3 },
    notes: ["nuts", "honey", "tea"],
    description: "水晶が採れることに由来する山脈名を冠した、キューバ最高峰の銘柄。ブルーマウンテンと同じティピカ系の血統で、クセのない上品な甘みと透明感のある後味。「キューバのブルマン」と呼ばれる所以。",
  },
  {
    id: "chn-yunnan",
    name: "雲南 ウォッシュド",
    country: "中国", region: "雲南省 プーアル", flag: "🇨🇳",
    process: "ウォッシュド", roast: "medium", price: 750,
    variety: "カティモール", altitude: "1,000〜1,700m", harvest: "11月〜3月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 3, aroma: 3, fruity: 3 },
    notes: ["berry", "caramel", "chocolate"],
    description: "お茶の名産地・雲南省で近年品質が急伸している新興産地。プラムのような果実感とキャラメルの甘み。アジアのコーヒーの新しい可能性を感じさせる一本。",
  },
  {
    id: "vnm-dalat",
    name: "ダラット アラビカ",
    country: "ベトナム", region: "ラムドン省 ダラット", flag: "🇻🇳",
    process: "ウォッシュド", roast: "mediumdark", price: 650,
    variety: "カティモール / ブルボン", altitude: "1,400〜1,600m", harvest: "10月〜3月",
    brew: ["フレンチプレス", "エスプレッソ"],
    profile: { acidity: 2, body: 4, sweetness: 4, bitterness: 3, aroma: 3, fruity: 2 },
    notes: ["chocolate", "nuts", "caramel"],
    description: "ロブスタ大国ベトナムで例外的にアラビカが育つ高原地帯ダラット産。ミルクチョコのような甘苦さで、カフェオレ向けブレンドのベースに好適。",
  },
  {
    id: "dom-barahona",
    name: "バラオナ",
    country: "ドミニカ共和国", region: "バラオナ", flag: "🇩🇴",
    process: "ウォッシュド", roast: "medium", price: 760,
    variety: "ティピカ / カトゥーラ", altitude: "600〜1,100m", harvest: "10月〜3月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["nuts", "caramel", "honey"],
    description: "カリブ海に浮かぶドミニカ共和国、南西部の山岳地帯バラオナ産。ナッツの香ばしさとまろやかな甘みで、クセがなく飲みやすい。カリブ海のコーヒーの中でも特に上品な仕上がり。",
  },
  {
    id: "hti-bleumontagne",
    name: "ブルーモンターニュ",
    country: "ハイチ", region: "マッシフ・ド・ラ・セル", flag: "🇭🇹",
    process: "ウォッシュド", roast: "medium", price: 820,
    variety: "ティピカ", altitude: "1,000〜1,600m", harvest: "8月〜1月",
    brew: ["ハンドドリップ", "サイフォン"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 3 },
    notes: ["floral", "honey", "nuts"],
    description: "ジャマイカのブルーマウンテンとは同じティピカ品種・同じ植民地期の伝播ルート（18世紀にイスパニョーラ島からジャマイカへ苗が渡った）を持つ兄弟豆だが、山系は別（両国は約190kmの海峡を挟んだ別の島）。コーヒー史に古くから名を残す銘柄で、近年生産量が激減した幻の豆。フローラルな香りと上品な甘みが特徴。",
  },
  {
    id: "ecu-galapagos",
    name: "ガラパゴス",
    country: "エクアドル", region: "サンクリストバル島", flag: "🇪🇨",
    process: "ウォッシュド", roast: "light", price: 1450,
    variety: "ティピカ / ブルボン", altitude: "300〜600m", harvest: "11月〜2月（雨季）",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 1, aroma: 4, fruity: 4 },
    notes: ["citrus", "tropical", "honey"],
    description: "世界自然遺産ガラパゴス諸島で、外来種規制の中わずかに栽培される希少な豆。海洋性気候由来の穏やかな酸味とトロピカルな甘さがあり、生産量の少なさから「幻の島コーヒー」とも呼ばれる。",
  },
  {
    id: "uga-rwenzori",
    name: "ルウェンゾリ",
    country: "ウガンダ", region: "ルウェンゾリ山地", flag: "🇺🇬",
    process: "ウォッシュド", roast: "medium", price: 700,
    variety: "SL14 / ブルボン", altitude: "1,500〜1,900m", harvest: "10月〜2月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 3, body: 3, sweetness: 3, bitterness: 3, aroma: 3, fruity: 3 },
    notes: ["citrus", "chocolate", "nuts"],
    description: "「月の山」の異名を持つ赤道直下の霊峰ルウェンゾリ山麓産。東アフリカらしい柑橘系の酸味にチョコの香ばしさが重なる、バランス型の実力派。ロブスタ輸出大国ウガンダの、知られざるアラビカの実力を示す一本。",
  },
  {
    id: "phl-barako",
    name: "バラコ",
    country: "フィリピン", region: "バタンガス", flag: "🇵🇭",
    process: "ウォッシュド", roast: "mediumdark", price: 890,
    variety: "リベリカ種", altitude: "300〜700m", harvest: "10月〜2月",
    brew: ["フレンチプレス", "エスプレッソ"],
    profile: { acidity: 1, body: 4, sweetness: 3, bitterness: 4, aroma: 4, fruity: 1 },
    notes: ["spice", "tropical", "earthy"],
    description: "アラビカ・ロブスタと並ぶ「コーヒー第三の原種」リベリカ種。世界的にも極めて希少で、フィリピンの伝統産地バタンガスが主産地。ジャックフルーツを思わせる独特のスパイシーな香りとタバコ的な重厚感を持つ、通好みの一本。",
  },
  {
    id: "twn-alishan",
    name: "阿里山",
    country: "台湾", region: "嘉義県 阿里山", flag: "🇹🇼",
    process: "ウォッシュド", roast: "light", price: 1150,
    variety: "ティピカ / SL34", altitude: "1,200〜1,600m", harvest: "10月〜1月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 1, aroma: 4, fruity: 4 },
    notes: ["floral", "honey", "citrus"],
    description: "近年国際品評会で急速に評価を上げる台湾産スペシャルティの代表格。烏龍茶の産地としても知られる高山の霧が、フローラルで蜜のような甘さを持つ繊細な味わいを育む。",
  },
  {
    id: "tha-doichaang",
    name: "ドイチャーン",
    country: "タイ", region: "チェンライ県 ドイチャーン",  flag: "🇹🇭",
    process: "ウォッシュド", roast: "medium", price: 850,
    variety: "カティモール / ティピカ", altitude: "1,200〜1,500m", harvest: "11月〜2月",
    brew: ["ハンドドリップ", "フレンチプレス"],
    profile: { acidity: 3, body: 3, sweetness: 4, bitterness: 2, aroma: 3, fruity: 3 },
    notes: ["caramel", "citrus", "nuts"],
    description: "タイ北部の山岳民族が手がける、東南アジア新興産地のホープ。かつて麻薬栽培が行われた土地をコーヒーに転換した歴史を持つ。キャラメルの甘みと穏やかな酸味で飲みやすい。",
  },
  {
    id: "reu-bourbonpointu",
    name: "ブルボン・ポワントゥ",
    country: "レユニオン島（フランス）", region: "レユニオン島", flag: "🇷🇪",
    process: "ウォッシュド", roast: "light", price: 3500,
    variety: "ブルボン・ポワントゥ（ブルボン種の突然変異）", altitude: "400〜800m", harvest: "6月〜9月",
    brew: ["ハンドドリップ"],
    profile: { acidity: 3, body: 2, sweetness: 5, bitterness: 1, aroma: 5, fruity: 3 },
    notes: ["floral", "honey", "tea"],
    description: "18世紀にレユニオン島へ持ち込まれたブルボン種から、19世紀初頭（1810年頃）に見出された自然突然変異。実が尖った形になることが名前の由来。低収量ゆえに一度は市場から姿を消したとされたが、1999年に再発見され復活を遂げた「幻のブルボン」。カフェイン含有量が通常の半分程度という特異な性質を持ち、はちみつのような甘さと紅茶を思わせる繊細な香りが特徴。",
  },
  {
    id: "mwi-misuku",
    name: "ミスクハイランド",
    country: "マラウイ", region: "ミスク・ヒルズ", flag: "🇲🇼",
    process: "ウォッシュド", roast: "medium", price: 780,
    variety: "ゲイシャ / アガロ", altitude: "1,600〜2,050m", harvest: "5月〜9月",
    brew: ["ハンドドリップ", "エアロプレス"],
    profile: { acidity: 4, body: 3, sweetness: 4, bitterness: 2, aroma: 4, fruity: 4 },
    notes: ["berry", "citrus", "floral"],
    description: "マラウイ最高峰の高地で、実はゲイシャ種も栽培されているアフリカの隠れた実力派産地。ベリーの果実味と柑橘の酸味が重なる、ケニアとエチオピアの中間のような表情を持つ。",
  },
  {
    id: "shn-sthelena",
    name: "セントヘレナコーヒー",
    country: "セントヘレナ（英領）", region: "セントヘレナ島", flag: "🇸🇭",
    process: "ウォッシュド", roast: "light", price: 4200,
    variety: "グリーンティップ・ブルボン", altitude: "500〜700m", harvest: "10月〜2月",
    brew: ["ハンドドリップ"],
    profile: { acidity: 3, body: 2, sweetness: 4, bitterness: 1, aroma: 4, fruity: 3 },
    notes: ["floral", "honey", "citrus"],
    description: "ナポレオンが流刑地での晩年に愛飲したという逸話で名高い、絶海の孤島セントヘレナ島産。年間生産量がごくわずかで世界最高額クラスの豆のひとつ。優しい酸味と上品な甘さ、フローラルな香りを持つ、まさに「幽閉の中の贅沢」。",
  },
];
